/** 原型用的虚构渠道名，按域名排序后依次分配，避免展示真实站点 */
export const CHANNEL_NAMES: { name: string; slug: string }[] = [
  { name: "青柚 API", slug: "qingyou" },
  { name: "北辰中转", slug: "beichen" },
  { name: "墨鲸 AI", slug: "mojing" },
  { name: "橙光 Token", slug: "chengguang" },
  { name: "鹿鸣 API", slug: "luming" },
  { name: "松果 Hub", slug: "songguo" },
  { name: "蓝湾 Code", slug: "lanwan" },
  { name: "星河中转", slug: "xinghe" },
  { name: "白桦 API", slug: "baihua" },
  { name: "赤兔 Relay", slug: "chitu" },
  { name: "飞梭 AI", slug: "feisuo" },
  { name: "千帆 Token", slug: "qianfan" },
  { name: "岚山 API", slug: "lanshan" },
  { name: "渡口中转", slug: "dukou" },
  { name: "潮汐 Hub", slug: "chaoxi" },
  { name: "回声 API", slug: "huisheng" },
  { name: "灯塔 Code", slug: "dengta" },
  { name: "小满 AI", slug: "xiaoman" },
  { name: "惊蛰中转", slug: "jingzhe" },
  { name: "谷雨 API", slug: "guyu" },
  { name: "芒种 Token", slug: "mangzhong" },
  { name: "白露 Relay", slug: "bailu" },
  { name: "寒露 API", slug: "hanlu" },
  { name: "冬至 Hub", slug: "dongzhi" },
  { name: "米粒 API", slug: "mili" },
  { name: "银杏中转", slug: "yinxing" },
  { name: "苍穹 AI", slug: "cangqiong" },
  { name: "极光 Code", slug: "jiguang" },
  { name: "山海 API", slug: "shanhai" },
  { name: "云雀 Token", slug: "yunque" },
  { name: "烛龙中转", slug: "zhulong" },
  { name: "鲸落 API", slug: "jingluo" },
  { name: "麦穗 Hub", slug: "maisui" },
  { name: "晨曦 AI", slug: "chenxi" },
  { name: "雾凇 API", slug: "wusong" },
  { name: "琥珀 Relay", slug: "hupo" },
  { name: "珊瑚中转", slug: "shanhu" },
  { name: "竹影 API", slug: "zhuying" },
  { name: "玄鸟 Code", slug: "xuanniao" },
  { name: "流萤 Token", slug: "liuying" },
  { name: "秋水 API", slug: "qiushui" },
  { name: "长风中转", slug: "changfeng" },
  { name: "朝暮 AI", slug: "zhaomu" },
  { name: "拾光 API", slug: "shiguang" },
  { name: "远山 Hub", slug: "yuanshan" },
  { name: "溪桥 API", slug: "xiqiao" },
  { name: "半夏 Relay", slug: "banxia" },
  { name: "木槿中转", slug: "mujin" },
  { name: "青禾 API", slug: "qinghe" },
  { name: "落雁 Token", slug: "luoyan" },
  { name: "南风 AI", slug: "nanfeng" },
  { name: "北冥 API", slug: "beiming" },
  { name: "东篱 Code", slug: "dongli" },
  { name: "西洲中转", slug: "xizhou" },
  { name: "听雨 API", slug: "tingyu" },
  { name: "观澜 Hub", slug: "guanlan" },
  { name: "临川 AI", slug: "linchuan" },
  { name: "望舒 API", slug: "wangshu" },
  { name: "扶摇 Relay", slug: "fuyao" },
  { name: "九章中转", slug: "jiuzhang" },
  { name: "司南 API", slug: "sinan" },
  { name: "河图 Token", slug: "hetu" },
  { name: "璇玑 AI", slug: "xuanji" },
  { name: "天工 API", slug: "tiangong" },
];
